#!/usr/bin/env bash
###############################################################################
# ~/.config/dircolors
#
# gnzsnz dotfiles
#
# colorfull bash settings
#
###############################################################################

COLORS=~/.config/"$THEME".dircolors

if [ "$(which dircolors)" ]; then

  eval "$(dircolors -b "$COLORS")"
  alias ls='ls --color=auto'
  #alias dir='dir --color=auto'
  #alias vdir='vdir --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
else
  export CLICOLOR=1
  export LSCOLORS=ExFxBxDxCxegedabagacad
fi
